# Generated by Django 6.0.7 on 2026-10-01 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_alter_target_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='targets.target')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('target', 'date'), name='unique_target_completion_per_day')],
            },
        ),
    ]
